### ISSUE TITLE
도커 이미지 생성하기

### ISSUE THREAD

**Issue by sinna94** [hyper-web-space/live-chat-api#5]
* 도커 이미지 생성
* docker-compose 예시 작성

**Comment by HyunBaeJung** [comment]
@sinna94 port가 달라서 cors 설정 해줘야 할듯,
선호하는 port있는게 아니면 vite default 5173 port 예외처리 부탁
<img width="540" alt="스크린샷 2023-04-16 오후 12 59 21" src="https://user-images.githubusercontent.com/42843734/232265707-021b8bf9-3844-4614-9a2f-3d2a75ee307b.png">
